spring:
  application:
    name: user-service

server:
  port: 9094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    hostname: localhost