services:
  wallet:
    image: operations
    build: .
    ports:
      - "8088:8081"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=operations
    ports:
      - "5432:5432"
  operations:
    image: operations
    build: .
    ports:
      - "9093:8090"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_DB=operations

