spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: operationModules
          uri: lb://OPERATION-SERVICE
          predicates:
            - Path=/api/v1/operations/**
          filters:
            - AuthFilter
        - id: walletModules
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/v1/wallets/**
          filters:
            - AuthFilter
        - id: userModules
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter
        - id: userSignIn
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/signIn
        - id: eureka-server
          uri: http://localhost:9090/
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:9090/
          predicates:
            - Path=/eureka/**
      discovery:
        locator:
          enabled: true

server:
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    hostname: localhost
