services:
  gateway:
    image: gateway
    build: .
    ports:
      - "8089:8081"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gateway
    ports:
      - "5433:5432"

