spring:
  application:
    name: operation-service

server:
  port: 9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    hostname: localhost